Feature/display player
AbdullahNanaDVT/Kick-Starter pull request #15
Opened 2021-11-16 10:00 UTC by AbdullahNanaDVT

Allows the user to view all the players in the squad for each team.

![Simulator Screen Shot - iPhone 13 Pro - 2021-11-16 at 11 52 03](https://user-images.githubusercontent.com/79845386/141963618-d2ef8dca-6a6a-42ee-b4f1-1b8539f87f0e.png)

2021-11-16 21:23 UTC, VincentMoyo approved these changes

2021-11-17 05:04 UTC, bgouws requested changes
Just some clean up 😄

2021-11-17 05:04 UTC, bgouws commented on Kick-Starter/Kick-Starter/Display Players/DisplayPlayersViewModel.swift
> +    private(set) var playerResponse: PlayerResponseModel?
Do these need to be `private(set)` ?

2021-11-17 05:04 UTC, bgouws commented on Kick-Starter/Kick-Starter/Teams Information/TeamsInformationViewController.swift
> +    @IBAction func didTapVenueButton(_ sender: Any) {
Private

2021-11-17 05:04 UTC, bgouws commented on Kick-Starter/Kick-Starter/Teams Information/TeamsInformationViewController.swift
> +    @IBAction func didTapPlayersButton(_ sender: Any) {
Private

2021-11-17 05:04 UTC, bgouws commented on Kick-Starter/Kick-Starter/Teams Information/TeamsInformationViewModel.swift
> +final class TeamsInformationViewModel {
You can add some line breaks in this class to make things a little more readable 😄

2021-11-17 20:31 UTC, bgouws approved these changes

2021-11-17 20:31 UTC, bgouws commented
Just a note but you could add a title to this screen as well 😄

2021-11-18 05:59 UTC, merged